### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by MurhafSousli** [EyeSeeTea/user-app#13]
Hi, 
I'm getting CORS error recently!

![image](https://user-images.githubusercontent.com/8130692/30515988-76906a1a-9b3b-11e7-9c6f-880902438421.png)

The app doesn't open anymore.

**Comment by tokland** [comment]
You're right, yesterday we updated the DB, try again. Do you have admin rights on the server? http://dev.eyeseetea.com:8080/dhis-web-settings/#/access

**Comment by adrianq** [comment]
@tokland Murhaf is using the 'old' admin user. I have just tested and seems to be working fine. Is it working for you @MurhafSousli ? Sometimes I need to open another tab in the browser and just keep the user logged at http://dev.eyeseetea.com:8080.

**Comment by MurhafSousli** [comment]
@tokland @adrianq  It is working now!
