### ISSUE TITLE
Improve right side panel

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#2]
Adding more information (User roles, User groups, OU Data Capture, OU Output) to the right side panel.

**Comment by tokland** [comment]
See src/List/DetailsBox.component.js

**Comment by MurhafSousli** [comment]
@adrianq @tokland I see most of these fields are `undefined` . Can you confirm each field with its correct property

**User roles** => ?
**User groups** => userGroups
**OU Data Capture** => dataViewOrganizationUnits
**OU Output** => organizationUnits

Here is a random instance of `props.source` which represent the data for a selected user

![image](https://user-images.githubusercontent.com/8130692/30329879-4add0a20-97dc-11e7-8fea-10a3c461a066.png)

**Comment by tokland** [comment]
When a field in a model is undefined, it may be that it's undefined or, more probably, the query has not asked for some fields. Check the fields being requested here:

https://github.com/EyeSeeTea/user-app/blob/master/src/List/list.store.js

Locate at the network tab the request being made so you can play with the URL. 

The dhis2 is quite powerful, spend some time with the docs to familriaze yourself:

https://docs.dhis2.org/master/en/developer/html/webapi.html

This covers the users' endpoint specifically:

https://docs.dhis2.org/master/en/developer/html/webapi_users.html

**Comment by MurhafSousli** [comment]
@tokland Yes I got the query thing it seems similar to GraphQL to me, isn't it? 

I was unable to extract the data from the `userGroups` field, the response looks different than the one in the documentation. The docs shows simple json data, but I ones I see are functions wrapped in an object as the console shows and when I try to use any of them I get `function does not exist` on that property!

Let's assume `value = props.source['userGroups']`

```js
case 'userGroups':
     console.log(value);
     console.log(value.valuesContainerMap);
     console.log(value.valuesContainerMap.values());
     return (<ul>
               {/*{value.valuesContainerMap.map(group => <li key={group.id}>{group.id}</li>)}*/}
          </ul>);
```
![image](https://user-images.githubusercontent.com/8130692/30381813-2e62e142-98a6-11e7-919a-cc81fdd32903.png)


Any hints?

**Comment by MurhafSousli** [comment]
@adrianq @tokland I have the same issue in #1, these properties are inaccessible, maybe I need to use a specific class from javascript API, but I couldn't any find information about it. The docs cover only the REST 
API not the javascript API.

**Comment by adrianq** [comment]
Hey @MurhafSousli ! Sorry for the late response. I will have a look at this asap and come back to you!

**Comment by adrianq** [comment]
@MurhafSousli I have just committed the code in this branch https://github.com/EyeSeeTea/user-app/tree/example-uo-in-details with a very simple example for user groups. The line you are interested in is this one I think: https://github.com/EyeSeeTea/user-app/commit/bc87ded525c9788b71c1839cfd9d19b4609826ab#diff-3f783c9074ac4c268b871dac8a540b69R89 It should be straight-forward to add the rest of the fields.
