### ISSUE TITLE
Differentiate assign org unit and assign org unit output

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#21]
Look here src/List/organisation-unit-dialog/OrgUnitDialog.component.js

**Comment by adrianq** [comment]
- [ ] Assign to Organization Unit and Assign to Organization Unit Output are two context actions on the landing page. At the moment the two of them perform the same action: updating both organization units. Each of them should perform a different action.
- [ ] Change from organization to organisation

**Comment by tokland** [comment]
Closed by https://github.com/EyeSeeTea/user-app/pull/29
