### ISSUE TITLE
Edit action

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#3]
- [ ] Create sqlview on app startup.
- [ ] Execute sqlview and retrieve data to build edit URL
- [ ] Add edit action to contextual menu (single selection)

Edit application needs the user id instead of the user uid to work. In order to get the user id a sqlview is needed. The approach we recommend (and the one we have follow in some other apps) is to create the sqlview on-the-fly. Everytime the app is executed an API call is triggered to verify if the sqlview already exists otherwise it creates it. The most common use case is that the person that installs the app executes it at least once to verify it works properly. This very first time the sqlview will be created making the app to work smoothly from now on.

**Comment by adrianq** [comment]
This code can be 'extracted' from DataDictionary

**Comment by tokland** [comment]
For the record: sqlViews are limited, they cannot access certain table (users is one of them) nor do certain operations (create). See ./dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlView.java for details.

For this reason, we cannot create a sqlView that gets the userid not create a PL/pgSQL function on-the-fly (as we cannot create anything. Anonymous blocks unfortunately cannot return values).

So, for now we'll link to the list of users filtered by username. If we really need to go to the edit page, we'll have to parse the HTML and get the data-id attribute.
