### ISSUE TITLE
Sort by columns

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#6]

**Comment by tokland** [comment]
Tables are implemented in d2-ui:

d2-ui/src/data-table/DataTableRow.component.js
d2-ui/src/data-table/DataTable.component.js
d2-ui/src/data-table/DataTableContextMenu.component.js
d2-ui/src/data-table/DataTableHeader.component.js

Ideally, changes should be done in a branch of d2-ui (working with a npm link) so we can use this in any other project. If that's not possible, copy the components to the app.

Proposal: Add to the state a sorting key: `{... sort: {column: NAME, order: "asc" | "desc"}, ...}`

**Comment by adrianq** [comment]
@tokland Is [this PR](https://github.com/EyeSeeTea/dataset-configuration/pull/121/files) a good example to keep in mind  for this task?

**Comment by tokland** [comment]
That's how I'd do it, yes (I used an array for `sorting` instead of the object I proposed in my previous comment, but that's a detail). I didn't link to it because I thought it might confuse Murhaf. Note that there is extra code on MultipleDataTable to handle prop onColumnSort.

**Comment by adrianq** [comment]
- [ ] Depends on #5 so we will need to review this after #5 is merged
- [ ] Remove sorting for fields with multiple values (like userroles,  OUDataCapture, etc)
- [ ] Review and merge

**Comment by tokland** [comment]
Refactored and merged to development. Now sorting is made with API calls, not JS code. Note that username is not sortable either, the API does not support sorting on nested fields (i.e. userCredentials.username).
