### ISSUE TITLE
Feedback needs to behave different whether we are at NRC or WHO server

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#78]
- NRC -> Internal Message
- WHO -> Github issue

**Comment by tokland** [comment]
Idea: Run a custom script in package.json ("d2-manifest" -> &&) that adds feedback info to manifest in key "feedback", read from env: FEEDBACKJS="feedback-who.json" yarn d2-manifest

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/user-app/pull/80
